### ISSUE TITLE
HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by ecureuill** [pysheng/pysheng#26]
**Debian Jessie 
pysheng-0.1**

pysheng bojwCgAAQBAJ
Traceback (most recent call last):
  File "/usr/local/bin/pysheng", line 6, in <module>
    sys.exit(pysheng.main(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/pysheng/download.py", line 119, in main
    for info, page, image_data in download_book(url):
  File "/usr/local/lib/python2.7/dist-packages/pysheng/download.py", line 104, in download_book
    image_data = download(image_url, opener=opener)
  File "/usr/local/lib/python2.7/dist-packages/pysheng/download.py", line 90, in download
    return lib.download(*args, **dict(kwargs, agent=AGENT))
  File "/usr/local/lib/python2.7/dist-packages/pysheng/lib.py", line 56, in download
    return opener.open(request).read()
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
`

**Comment by tokland** [comment]
I am not actively developing this package anymore, sorry, I hope some user with Python experience can take it in a fork.

**Comment by michaelcoyote** [comment]
I'm unable to recreate this issue.   
`michael@whistlesgowoo:~/working/tools/pysheng (master)$ pysheng bojwCgAAQBAJ
Downloaded Patricia Elizabeth Spencer, Lynne Sanford Koester - Nurturing Language and Learning/001.png
...
`
